repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: local
  hooks:
    - id: lint
      name: Lint
      entry: make lint
      language: system
      types: [python]

    - id: format
      name: Format
      entry: make format
      language: system
      types: [python]
