from __future__ import annotations

from .arithmetic import (
    Add,
    ArithmeticAttributes,
    Divide,
    Multiply,
    Subtract,
    add,
    divide,
    multiply,
    subtract,
)
from .array import (
    Constant,
    ConstantAttributes,
    Reshape,
    Slice,
    Transpose,
    constant,
    reshape,
    slice_array,
    transpose,
)
from .control_flow import (
    Conditional,
    ConditionalAttributes,
    While,
    WhileAttributes,
    conditional,
    while_loop,
)
from .inputs import (
    Input,
    InputAttributes,
    InputType,
    Parameter,
    Placeholder,
    Resource,
    parameter,
    placeholder,
    resource,
)
from .matrix import MatMul, MatMulAttributes, matmul
from .nn import (
    Conv2D,
    Conv2DAttributes,
    PadMode,
    Pool2D,
    Pool2DAttributes,
    PoolMode,
    avg_pool2d,
    conv2d,
    max_pool2d,
)
from .nn_ops import (
    Activation,
    ActivationAttributes,
    ActivationType,
    BatchNorm,
    BatchNormAttributes,
    Dropout,
    DropoutAttributes,
    Phase,
    batch_norm,
    dropout,
    elu,
    relu,
    sigmoid,
    softmax,
    tanh,
)
from .primitives import (
    Im2Col,
    Im2ColAttributes,
    ReduceAttributes,
    ReduceMax,
    ReduceSum,
    im2col,
    reduce_max,
    reduce_sum,
)

__all__ = [
    # Types and enums
    "ActivationType",
    "InputType",
    "PadMode",
    "PoolMode",
    "Phase",
    # Attributes
    "ArithmeticAttributes",
    "ConstantAttributes",
    "InputAttributes",
    "ConditionalAttributes",
    "WhileAttributes",
    "Conv2DAttributes",
    "Pool2DAttributes",
    "BatchNormAttributes",
    "DropoutAttributes",
    "ActivationAttributes",
    "Im2ColAttributes",
    "ReduceAttributes",
    "MatMulAttributes",
    # Operation classes
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "Constant",
    "Reshape",
    "Transpose",
    "Slice",
    "Input",
    "Placeholder",
    "Parameter",
    "Resource",
    "Conditional",
    "While",
    "Conv2D",
    "Pool2D",
    "BatchNorm",
    "Dropout",
    "Activation",
    "Im2Col",
    "ReduceMax",
    "ReduceSum",
    "MatMul",
    # Helper functions - Arithmetic
    "add",
    "subtract",
    "multiply",
    "divide",
    # Helper functions - Array
    "constant",
    "reshape",
    "transpose",
    "slice_array",
    # Helper functions - Input
    "placeholder",
    "parameter",
    "resource",
    # Helper functions - Control Flow
    "conditional",
    "while_loop",
    # Helper functions - Neural Network
    "conv2d",
    "max_pool2d",
    "avg_pool2d",
    "batch_norm",
    "dropout",
    "relu",
    "sigmoid",
    "tanh",
    "elu",
    "softmax",
    # Helper functions - Primitive
    "im2col",
    "reduce_max",
    "reduce_sum",
    # Helper functions - Matrix
    "matmul",
]
